// VISITS
export const GET_VISITS = 'GET_VISITS';
export const GET_VISITS_SUCCESS = 'GET_VISITS_SUCCESS';
export const GET_VISITS_ERROR = 'GET_VISITS_ERROR';

export const GET_VISIT = 'GET_VISIT';
export const GET_VISIT_SUCCESS = 'GET_VISIT_SUCCESS';
export const GET_VISIT_ERROR = 'GET_VISIT_ERROR';

export const PUT_VISIT = 'PUT_VISIT';
export const PUT_VISIT_SUCCESS = 'PUT_VISIT_SUCCESS';
export const PUT_VISIT_ERROR = 'PUT_VISIT_ERROR';

export const POST_VISIT = 'POST_VISIT';
export const POST_VISIT_SUCCESS = 'POST_VISIT_SUCCESS';
export const POST_VISIT_ERROR = 'POST_VISIT_ERROR';

export const DELETE_VISIT = 'DELETE_VISIT';
export const DELETE_VISIT_SUCCESS = 'DELETE_VISIT_SUCCESS';
export const DELETE_VISIT_ERROR = 'DELETE_VISIT_ERROR';


//USERS
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const GET_ME = 'GET_ME';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_ERROR = 'GET_ME_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const POST_USER = 'POST_USER';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_ERROR = 'POST_USER_ERROR';

export const PUT_USER = 'PUT_USER';
export const PUT_USER_SUCCESS = 'PUT_USER_SUCCESS';
export const PUT_USER_ERROR = 'PUT_USER_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const POST_USER_AVATAR = 'POST_USER_AVATAR';
export const POST_USER_AVATAR_SUCCESS = 'POST_USER_AVATAR_SUCCESS';
export const POST_USER_AVATAR_ERROR = 'POST_USER_AVATAR_ERROR';


//SERVICES
export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_ERROR = 'GET_SERVICES_ERROR';

export const GET_SERVICE = 'GET_SERVICE';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_ERROR = 'GET_SERVICE_ERROR';

export const POST_SERVICE = 'POST_SERVICE';
export const POST_SERVICE_SUCCESS = 'POST_SERVICE_SUCCESS';
export const POST_SERVICE_ERROR = 'POST_SERVICE_ERROR';

export const PUT_SERVICE = 'PUT_SERVICE';
export const PUT_SERVICE_SUCCESS = 'PUT_SERVICE_SUCCESS';
export const PUT_SERVICE_ERROR = 'PUT_SERVICE_ERROR';

export const DELETE_SERVICE = 'DELETE_SERVICE';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_ERROR = 'DELETE_SERVICE_ERROR';


//CLIENTS
export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_ERROR = 'GET_CLIENTS_ERROR';

export const GET_CLIENT = 'GET_CLIENT';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';
export const GET_CLIENT_ERROR = 'GET_CLIENT_ERROR';

export const POST_CLIENT = 'POST_CLIENT';
export const POST_CLIENT_SUCCESS = 'POST_CLIENT_SUCCESS';
export const POST_CLIENT_ERROR = 'POST_CLIENT_ERROR';

export const PUT_CLIENT = 'PUT_CLIENT';
export const PUT_CLIENT_SUCCESS = 'PUT_CLIENT_SUCCESS';
export const PUT_CLIENT_ERROR = 'PUT_CLIENT_ERROR';

export const DELETE_CLIENT = 'DELETE_CLIENT';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_ERROR = 'DELETE_CLIENT_ERROR';


//COMPANIES
export const GET_COMPANIES = 'GET_COMPANIES';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_ERROR = 'GET_COMPANIES_ERROR';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_ERROR = 'GET_COMPANY_ERROR';

export const POST_COMPANY = 'POST_COMPANY';
export const POST_COMPANY_SUCCESS = 'POST_COMPANY_SUCCESS';
export const POST_COMPANY_ERROR = 'POST_COMPANY_ERROR';

export const PUT_COMPANY = 'PUT_COMPANY';
export const PUT_COMPANY_SUCCESS = 'PUT_COMPANY_SUCCESS';
export const PUT_COMPANY_ERROR = 'PUT_COMPANY_ERROR';

export const DELETE_COMPANY = 'DELETE_COMPANY';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_ERROR = 'DELETE_COMPANY_ERROR';


//CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const POST_CATEGORY = 'POST_CATEGORY';
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR';

export const PUT_CATEGORY = 'PUT_CATEGORY';
export const PUT_CATEGORY_SUCCESS = 'PUT_CATEGORY_SUCCESS';
export const PUT_CATEGORY_ERROR = 'PUT_CATEGORY_ERROR';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

//PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';

export const POST_PRODUCT = 'POST_PRODUCT';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_ERROR = 'POST_PRODUCT_ERROR';

export const PUT_PRODUCT = 'PUT_PRODUCT';
export const PUT_PRODUCT_SUCCESS = 'PUT_PRODUCT_SUCCESS';
export const PUT_PRODUCT_ERROR = 'PUT_PRODUCT_ERROR';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

//INVITATIONS
export const GET_INVITATIONS = 'GET_INVITATIONS';
export const GET_INVITATIONS_SUCCESS = 'GET_INVITATIONS_SUCCESS';
export const GET_INVITATIONS_ERROR = 'GET_INVITATIONS_ERROR';

export const POST_INVITATION = 'POST_INVITATION';
export const POST_INVITATION_SUCCESS = 'POST_INVITATION_SUCCESS';
export const POST_INVITATION_ERROR = 'POST_INVITATION_ERROR';

export const PUT_INVITATION = 'PUT_INVITATION';
export const PUT_INVITATION_SUCCESS = 'PUT_INVITATION_SUCCESS';
export const PUT_INVITATION_ERROR = 'PUT_INVITATION_ERROR';

export const DELETE_INVITATION = 'DELETE_INVITATION';
export const DELETE_INVITATION_SUCCESS = 'DELETE_INVITATION_SUCCESS';
export const DELETE_INVITATION_ERROR = 'DELETE_INVITATION_ERROR';

// LOGIN
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';


// REGISTRARION
export const CHECK_IF_EXIST = 'CHECK_IF_EXIST';
export const CHECK_IF_EXIST_SUCCESS = 'CHECK_IF_EXIST_SUCCESS';
export const CHECK_IF_EXIST_ERROR = 'CHECK_IF_EXIST_ERROR';

export const CONFIRM_CODE = 'CONFIRM_CODE';
export const CONFIRM_CODE_SUCCESS = 'CONFIRM_CODE_SUCCESS';
export const CONFIRM_CODE_ERROR = 'CONFIRM_CODE_ERROR';

export const CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT';
export const CONFIRM_ACCOUNT_SUCCESS = 'CONFIRM_ACCOUNT_SUCCESS';
export const CONFIRM_ACCOUNT_ERROR = 'CONFIRM_ACCOUNT_ERROR';


