version: 2.1
orbs:
  node: circleci/node@12.16.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install 
            - run: npm build
            - run: node .circleci/deploy.js
workflows:
    build-and-test:
      jobs:
        - build-and-test